# Os outros arquivos irão herdar as configs deste
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  cloud:
    config:
      override-system-properties: false

# 100% das requisições serão rastreadas ( 1.0 = 100%, 0.1 = 10% )
management:
  tracing:
    sampling:
      probability: 1.0