spring:
  data:
    mongodb:
      username: user1
      password: password1
      host: localhost
      port: 27017
      databases: customer
      authentication-database: admin
server:
  port: 8090
