## Cria rotas automaticamente usando o Eureka (Service Discovery).
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/micro-services"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      ## Irá utilizar Load Balancer(lb) para quando receber a requisição para /api/v1/customers/**
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: order-lines-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-lines/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
server:
  port: 8222